#!/usr/bin/env python3
"""
Fetch the PandoDnD Warhorn atom feed and write the upcoming events
to _data/pando_schedule.yml so Jekyll can render them at build time.

Run locally:
    python scripts/refresh_pando.py

Run automatically by .github/workflows/refresh-pando-schedule.yml.
"""

from __future__ import annotations

import datetime as dt
import html
import re
import sys
import urllib.request
import xml.etree.ElementTree as ET
from pathlib import Path

# ─── Config ────────────────────────────────────────────────────────────────
FEED_URL = "https://warhorn.net/events/pandodnd/schedule/Ya7RynA9U_XsaE_Ve6Ht.atom"
OUTPUT   = Path(__file__).resolve().parent.parent / "_data" / "pando_schedule.yml"
MAX_EVENTS = 12  # keep ahead-looking events only, capped

ATOM_NS  = "{http://www.w3.org/2005/Atom}"
GD_NS    = "{http://schemas.google.com/g/2005}"


def fetch_feed(url: str) -> bytes:
    req = urllib.request.Request(
        url,
        headers={"User-Agent": "hoshisabi.github.io schedule refresher"},
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read()


def strip_html(text: str) -> str:
    """Collapse HTML-ish content into a single-line plain string."""
    if not text:
        return ""
    text = html.unescape(text)
    text = re.sub(r"<br\s*/?>", "\n", text, flags=re.I)
    text = re.sub(r"</p\s*>", "\n", text, flags=re.I)
    text = re.sub(r"<[^>]+>", "", text)
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n\s*\n+", "\n\n", text)
    return text.strip()


def pick_summary(content: str) -> str:
    """Extract a one- or two-sentence blurb from the entry content."""
    plain = strip_html(content)
    paragraphs = [p.strip() for p in plain.split("\n\n") if p.strip()]
    # Skip header lines like "Friday, May 27 — 2 hours" or seat lists.
    skip = re.compile(r"(players?|GM|CONTENT WARNING|Tier \d|hours)", re.I)
    for p in paragraphs:
        if len(p) >= 60 and not skip.search(p):
            return re.sub(r"\s+", " ", p)
    # Fallback: just the longest paragraph.
    return max(paragraphs, key=len, default="").strip()


def parse_title(raw: str) -> tuple[str, str]:
    raw = (raw or "").strip()
    m = re.match(r"^([A-Z0-9][A-Z0-9-]+)\s+(.*)$", raw)
    if m:
        return m.group(1), m.group(2).strip()
    return "", raw


def first_text(elem: ET.Element | None) -> str:
    return (elem.text or "").strip() if elem is not None else ""


def parse_entries(xml_bytes: bytes) -> list[dict]:
    root = ET.fromstring(xml_bytes)
    now = dt.datetime.now(dt.timezone.utc)
    out: list[dict] = []

    for entry in root.findall(f"{ATOM_NS}entry"):
        title_raw = first_text(entry.find(f"{ATOM_NS}title"))
        code, title = parse_title(title_raw)

        # Link (rel="alternate")
        link = ""
        for ln in entry.findall(f"{ATOM_NS}link"):
            if ln.get("rel", "alternate") == "alternate":
                link = ln.get("href", "")
                break

        # Start time — gd:when startTime
        when = entry.find(f"{GD_NS}when")
        start_raw = (when.get("startTime") if when is not None else "") or ""
        if not start_raw:
            continue
        try:
            start = dt.datetime.fromisoformat(start_raw.replace("Z", "+00:00"))
        except ValueError:
            continue
        if start.astimezone(dt.timezone.utc) < now:
            continue  # skip past events

        content = first_text(entry.find(f"{ATOM_NS}content"))
        summary = pick_summary(content)

        out.append({
            "code": code,
            "title": title,
            "date": start.isoformat(),
            "tier": "Tier 2 · APL 8 · 2 hours",  # leave hardcoded for now
            "summary": summary,
            "link": link or "https://warhorn.net/events/pandodnd",
        })

    out.sort(key=lambda e: e["date"])
    return out[:MAX_EVENTS]


def yaml_str(value: str) -> str:
    """Quote a string for YAML. Block scalar for long/multiline."""
    if not value:
        return '""'
    if "\n" in value:
        indented = "\n".join("    " + line for line in value.split("\n"))
        return ">-\n" + indented
    # Use double quotes; escape any embedded quotes.
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def render_yaml(entries: list[dict]) -> str:
    now_iso = dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat()
    lines: list[str] = [
        "# Upcoming PandoDnD schedule.",
        "# Generated by scripts/refresh_pando.py from the Warhorn atom feed.",
        "# Do not edit by hand — your changes will be overwritten on the next refresh.",
        "",
        f"source: {FEED_URL}",
        f"generated_at: {now_iso}",
        "",
        "entries:",
    ]
    if not entries:
        lines.append("  []")
    for e in entries:
        lines.append(f"  - code: {yaml_str(e['code'])}")
        lines.append(f"    title: {yaml_str(e['title'])}")
        lines.append(f"    date: {yaml_str(e['date'])}")
        lines.append(f"    tier: {yaml_str(e['tier'])}")
        lines.append(f"    summary: {yaml_str(e['summary'])}")
        lines.append(f"    link: {yaml_str(e['link'])}")
    return "\n".join(lines) + "\n"


def main() -> int:
    print(f"Fetching {FEED_URL}")
    try:
        xml_bytes = fetch_feed(FEED_URL)
    except Exception as exc:
        print(f"ERROR: feed fetch failed: {exc}", file=sys.stderr)
        return 1

    try:
        entries = parse_entries(xml_bytes)
    except ET.ParseError as exc:
        print(f"ERROR: feed parse failed: {exc}", file=sys.stderr)
        return 2

    yaml_text = render_yaml(entries)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(yaml_text, encoding="utf-8")
    print(f"Wrote {len(entries)} entries to {OUTPUT.relative_to(OUTPUT.parent.parent)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
